### ISSUE TITLE
Improved FoW

### ISSUE THREAD

**Issue by jensj12** [jensj12/MeesGame#94]
- [x] Make fog of war based on quarter cells.
 - [x] Reveal all tiles the player can see, not just the nine surrounding cells

**Comment by maxmeijer42** [comment]
How are we going to check whether a player can see something? Should a (quarter) cell be revealed when the player sees part of it, or only when he sees the middle, or only if he sees the entire (quarter) cell? 

And where exactly are the player's 'eye's? Are they in the middle of the tile, or in the middle of the sides of the tile?

Or do we want to base it on the player's position so that additional (quarter) cells can be revealed while the player is animating to his new position?

**Comment by jorisBarkema** [comment]
For now I wanted to start with another property for the tiles, obstructsVision, if it obstructs vision the light stops there otherwise it keeps going, with maybe a limit of 3/4/5 tiles.

I think I'm gonna divide the tiles in 9 sections, 4 corners, 4 sides and the center.

animating would be nice but I don't think it should be a priority for now.

**Comment by jensj12** [comment]
For simplicity, just keep the player's eyes in the center of the tile. Animating it would be nice but indeed not a priority.

My idea was to show all tiles the player can fully see (that is, no wall tiles), plus the surrounding quarter cells (which does include wall tiles).

Tiles are already divided over floor and wall tiles, so we can use that to check visibility. The revealed property of tiles just needs to be changed to an int for bitwise operations so drawing can be done with a spritesheet of black overlays.

**Comment by jorisBarkema** [comment]
Yeah I'll do quarters instead, with a spritesheet working the same way as the walls.

**Comment by maxmeijer42** [comment]
Don't implement your own bit flipping btw, because that gets messy and makes the code unnecessarily complicated. Use a [BitArray](http://stackoverflow.com/questions/8144349/what-is-the-c-sharp-equivalent-of-stdbitset-of-c) or some alternative

**Comment by jensj12** [comment]
Does that allow use as integer instead of bools? That allows quite some shortcuts.
